### ISSUE TITLE
Multiple console errors on index.html

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/for-each-lab#4]
When opening the console on `index.html`, multiple errors appear:

![foreach-console-errors](https://cloud.githubusercontent.com/assets/5466592/19862784/158302ac-9f68-11e6-997e-5109987c5d00.png)

It looks like Mocha and Expect aren't loading correctly, which makes it impossible to run tests in the browser. Running `npm install` does not resolve the issue.

I reproduced this in the IDE (version 1.9.0) on Mac OS X 10.11.6.

Reported by @jmtho.

**Comment by gj** [comment]
Running `npm install` within the IDE seems to just install everything on the Learn servers as opposed to within the local `.atom/code/labs/lab-name` directory.

If the student has a local dev environment set up (at a minimum, they'll need Node), they can navigate to the local lab directory and run `npm install` in there.
![](https://cloud.githubusercontent.com/assets/17556281/20472578/c155a8fc-af88-11e6-8a8d-410249bea89b.png)
Maybe @aturkewi has a better idea.

**Comment by aturkewi** [comment]
Hey @gj @ivalentine and @jmtho

So here is some quick background about the Learn IDE. None of the work you do with the Learn IDE is mean to be accessed directly on your computer. The files that are there are strictly for the use of the text editor. `npm install` only installs the packages on the Learn IDE server and not locally because we set up the Learn IDE so you wouldn't need a dev environment. 

If you're working on a file, the best way to do it is through the Learn IDE editor (the top part of the Learn IDE). If you want to view a file, the only way you should be doing this is _through the Learn server_. The easiest and most common way to do this is to run `httpserver`. This will start serving your lab _from the Learn server_ where the dev environment is set up and all the node packages are installed. This command will give you an IP address in the terminal that you can type into the browser to get things working. 

I'm going to close this issue on this lab because it's not really an issue with the lab, it pertains more to the Learn IDE in general and how it works. If any of you have any more questions though, please feel free to message me directly (@gj @ivalentine) or use the Ask A Question feature for more clarification (@jmtho).

I hope this was helpful :)
